### ISSUE TITLE
Set color of voltages and currents globally

### ISSUE THREAD

**Issue by ju-Julia** [circuitikz/circuitikz#321] opened 2019-11-19 09:30 UTC
I wanted to globally define the colors of current and voltage arrows bot not their label. I found these two approaches:
[1. Same color label](https://tex.stackexchange.com/questions/395372/circuitikz-change-current-arrow-color-and-label-color-at-once)
[2. Different color label](https://tex.stackexchange.com/questions/292835/circuittikz-colored-current-arrows)
What I don't like about the solution there (tell me, if you need example code for the issues):
- The color option has to be set for every drawing
- Voltage: Setting different colors for label and arrow is cumbersome
- Setting a color for the currents for the whole tikzpicture changes the color of voltage arrows too

So I'm interested, if there is a simpler solution to set the color of voltage and current arrows (and their labels) globally.

**Comment by Rmano** [comment] 2019-11-19 11:38
The problem with changing the color of voltage arrows and current arrows is that it is not designed in...  So really this would be an enhancement (marking as so). I'll have a look. 

Since 0.9.5, you can style the labels --- so it's not difficult to set the color of the labels globally, see pag. 112 in http://circuitikz.github.io/circuitikz/circuitikzmanualgit.pdf

**Comment by Rmano** [comment] 2019-11-19 12:00
I fear that changing the color of voltage arrows will be very complex. The problem is that the arrow is drawn as part of the path, and so the color is selected at the end of the path, as usual in `tikz`. To check it, see this code (pure `tikz`):

    \draw [color=black] (0,0) -- (1,0) {[color=red] (1,0) -- (2,0)} --(3,0);

which results in 

![image](https://user-images.githubusercontent.com/6414907/69144751-50988380-0acc-11ea-9c2f-548214bb4785.png)

...no red here! So that's impossible to fix without very big changes to the innards of `circuitikz`. You have to draw the voltage arrows by hand after the path, I fear.

**Comment by ju-Julia** [comment] 2019-11-20 09:05
Ok, I see. Thank you for analyzing this!

**Comment by Rmano** [comment] 2019-11-20 10:46
A workaround is to use the coordinates of the element and draw your own arrow --- so you have full control. For example: 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{circuitikz}[
    ]
    \draw (0,0) to[R, name=R] ++(3,0) to[C, name=C] ++(0,-3) node[ground]{};
    \draw[red, thick, -{Triangle[]}]
        ([shift={(-0.2,-0.2)}]R.left) to[bend right] 
        node[midway, below]{\SI{1}{V}}
        ([shift={(0.2,-0.2)}]R.right);
\end{circuitikz}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/69232396-45585d00-0b8b-11ea-8372-67c40e6aefaf.png)

...you can easily devise a macro for this kind of thing :-)

**Comment by Rmano** [comment] 2019-11-20 13:46
I will close this for now. Sorry for not be able to give a solution.

**Closed by Rmano** 2019-11-20 13:46 UTC
Labels: couldn't fix, enhancement

**Comment by Rmano** [comment] 2021-06-24 07:21
This answer is quite old now --- please have a look at https://texdoc.org/serve/circuitikz/0#subsection.5.8
