### ISSUE TITLE
American Voltage and Current Sources Can't Reverse Polarity

### ISSUE THREAD

**Issue by karlberggren** [circuitikz/circuitikz#32] opened 2016-05-02 01:57 UTC
I believe there is a bug wherein the american voltage sources cannot have polarity reversed using the v^>= and v^<= labeling operations.  A detail example is shown here:

https://www.overleaf.com/read/zsqbzpbfhhbq

I apologize if this was not the correct place to raise this issue.

**Comment by sistlind** [comment] 2016-05-02 06:50
Hi,
this should be already fixed in the latest release version 0.5 at commit 9309701, reported already as #19
At least at my local installation the output looks good:
![vsources](https://cloud.githubusercontent.com/assets/6959674/14948549/07a0c7c4-1042-11e6-8147-c5fb4371b792.PNG)

Perhaps this version is not yet included in overleaf? It was released last week.
You can check the version with the command \pgfcircversion
Just reopen this ticket, if the issue exists still at version 0.5

**Comment by karlberggren** [comment] 2016-05-02 10:43
You were correct.  Overleaf is running version 0.4.  I should have checked
that before reporting.  Sorry for wasting your time, and thank you for the
helpful response (and for fixing this issue!).



On Mon, May 2, 2016 at 2:50 AM, Stefan Lindner <notifications@github.com>
wrote:

> Hi,
> this should be already fixed in the latest release version 0.5 at commit
> 9309701
> <https://github.com/mredaelli/circuitikz/commit/9309701ec305c9a838a334bd4399c4e9b7f07463>,
> reported already as #19
> <https://github.com/mredaelli/circuitikz/issues/19>
> At least at my local installation the output looks good:
> [image: vsources]
> <https://cloud.githubusercontent.com/assets/6959674/14948549/07a0c7c4-1042-11e6-8147-c5fb4371b792.PNG>
>
> Perhaps this version is not yet included in overleaf? It was released last
> week.
> You can check the version with the command \pgfcircversion
> Just reopen this ticket, if the issue exists still at version 0.5
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mredaelli/circuitikz/issues/32#issuecomment-216117971>
>



-- 
Karl K. Berggren <http://www.rle.mit.edu/qnn/people_berggren.htm>
Prof. of Electrical Engineering
Quantum Nanostructures and Nanofabrication Group <http://quantum.mit.edu>
Director, NanoStructures Laboratory <http://www.rle.mit.edu/nsl/>, Research
Laboratory of Electronics
Undergraduate Lab Officer <http://www.rle.mit.edu/nsl/>, Dept. of EECS
Massachusetts Institute of Technology

**Comment by Rmano** [comment] 2021-09-22 07:17
Reporting the code here:

```latex
\documentclass[]{article}
\usepackage{circuitikz} 
\begin{document}

I believe I may have found a small bug in circuitikz.  You may 
already be aware of this.

When drawing American voltage sources, the polarity of the source does not switch back and forth with the <= and >= label operator.  An example of the situation is shown below, with the first set of symbols being european (where the expected behavior occurs) and the 2nd set being the american (where I would have expected the first two to have the - terminal on top instead of on the bottom).

\pgfcircversion

\begin{circuitikz} 
\draw
    (0,0) to [voltage source, v^<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}
\draw
    (0,0) to [voltage source, v_<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}
\draw
    (0,0) to [voltage source, v^>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}
\pgfcircversion;
\draw
    (0,0) to [voltage source, v_>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}

\begin{circuitikz}[american]
\draw
    (0,0) to [voltage source, v^<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}[american]
\draw
    (0,0) to [voltage source, v_<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}[american]
\draw
    (0,0) to [voltage source, v^>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}[american]
\draw
    (0,0) to [voltage source, v_>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}

the current sources seem to have the same issue

\begin{circuitikz}
\draw
    (0,0) to [current source, i^<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}
\draw
    (0,0) to [current source, i_<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}
\draw
    (0,0) to [current source, i^>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}
\draw
    (0,0) to [current source, i_>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}



\begin{circuitikz}[american]
\draw
    (0,0) to [current source, i^<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}[american]
\draw
    (0,0) to [current source, i_<=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}[american]
\draw
    (0,0) to [current source, i^>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}
\quad
\begin{circuitikz}[american]
\draw
    (0,0) to [current source, i_>=$\underline{U}_{in}$]
    (0,2)
;
\end{circuitikz}

\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/134299522-ec76b8c7-748d-4bdb-948d-ec9098fa9cdc.png)

**Comment by Rmano** [comment] 2021-09-22 07:23
Notice that the policy of `circuitikz` is not to make incompatible changes with older versions. So if you give no options to the loading of `circuitikz`, you have the old (that somebody thought buggy, somebody right) behavior.

If you apply `\usepackage[RPvoltages]{circuitikz}` the result will be different (but maybe not what you expect): the `v` label will *not* change the symbol orientation by design, only the *external* voltage label/sign. You need to use `invert` for the symbol internal signs. 

I know this is a bit of controversial thing, but it has been like that forever, and changing it will invalidate older circuit --- too big a change in my opinion.

**Comment by ArchangeGabriel** [comment] 2021-09-22 16:19
@Rmano: So it used to work at some point, then not in 0.4, then again from 0.5 to 0.8.2. So technically it has been changing several times already. Also I find id a bit sad to have four `v_>=`, `v_<=`, `v^>=` and `v^<=` commands for only two outputs…

But you’re right, I should be using RPvoltages, I actually use it in my code but when working on an MWE for tex.se I did not include it, could not find a way to have the voltage source in the correct direction and stumbled upon this issue.

**Comment by Rmano** [comment] 2021-09-22 17:34
@ArchangeGabriel yes, you right, it's a bit of a mess; you can see here: https://tex.stackexchange.com/questions/612425/change-circuitikz-vsource-current-arrow-direction#comment1531688_612437 (and in the following comments) what I think about it now. 

The four commands will have different outputs in non-generator devices, that you can force if you want (but I understand that in this case it has no sense).

**Comment by ArchangeGabriel** [comment] 2021-09-22 17:43
Well given the number of things that seems broken because of needing to keep retro-compatibility, I’d be in favour of a huge breaking release at this point, maybe using something like `mhchem`’s `version` key, or just a `modern` vs `legacy` (default) behaviour. But you’re the one in charge and doing actual development, so my opinion does not matter much. ;)

**Comment by Rmano** [comment] 2021-09-22 18:02
Well, that could be an option --- I just need to track what the changes should be. I really do not know much more apart from the eternal fight for voltage/current directions, and the detail if `v` should change the symbol direction... and in this case, I am not sure. Because now it's easy: symbols are never inverted by `v<`. To change this, I should add a flag to each symbol to say if it changes or not and a form to override. Consider for example: 

```latex
\documentclass[border=10pt]{standalone}
\usepackage[siunitx, RPvoltages]{circuitikz}
\begin{document}
\begin{tikzpicture}[european voltages]
    \draw (0,0) to[american voltage source, v=$v_1$] ++(0,2);
    \node at (1,1) {$=$};
    \draw (3,0) to[american voltage source, v<=$-v_1$] ++(0,2);
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/134397231-221853f1-7549-441a-8999-1fd221e0dc1b.png)

If `v` changes the direction of the symbol, the thing will become complex. We should add a non-invert option for the second one...

**Comment by Rmano** [comment] 2021-10-05 15:07
Closing, feel free to reopen if you want to comment!

**Closed by Rmano** 2021-10-05 15:07 UTC
Labels: duplicate
