### ISSUE TITLE
Equals sign in label causes errors

### ISSUE THREAD

**Issue by ChrisDryden** [circuitikz/circuitikz#280] opened 2019-09-06 19:58 UTC
When writing a label using the notation ```to[resistor, l={insert code here}]```

When attempting to write an equals sign inside the label, it is required to write the equals sign inside a bracket e.g. {=}. Otherwise its hard to deduce what the error is in the label and the diagram spews out random characters.

Is this something that could be fixed? I noticed its usage in the documentation.

**Comment by Rmano** [comment] 2019-09-06 22:05
It's explained in section 4.1, top of page 95 in current manual... It's a matter of how tikz processes the option list. 

![IMG_20190907_000023](https://user-images.githubusercontent.com/6414907/64463100-180b1f80-d103-11e9-96e0-36514457941b.jpg)

**Comment by Rmano** [comment] 2019-09-07 12:25
It's a duplicate of an issue filed by me ;-) #143 --- you can find a lot of references there. Will close, re-open if you find a way to fix it!

**Closed by Rmano** 2019-09-07 12:25 UTC
Labels: probaby won't fix
